
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: luigi-deployment
  labels:
    app: luigi
spec:
  selector:
    matchLabels:
      app: luigi
  template:
    metadata:
      labels:
        app: luigi
    spec:
      containers:
      - name: luigid
        image: farmbio/luigid
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: luigi-service
spec:
  ports:
  - name: http
    targetPort: 8082
    port: 8082
  selector:
    app: luigi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: luigid
spec:
  rules:
  - host: mtbls233.uservices.cloud
    http:
      paths:
      - path: /luigi
        backend:
          serviceName: luigi-service
          servicePort: http
