- hosts: master
  gather_facts: False
  vars:
    sha1_pass: "{{lookup('file', '{{playbook_dir}}/../.secret') | trim}}"
  tasks:
    - template:
        src: template.j2
        dest: /tmp/deployment.yml
    - command: >
        kubectl
        apply
        -f /tmp/deployment.yml
