---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jupyter-deployment
  labels:
    app: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: notebook
        image: jupyter/datascience-notebook
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  ports:
  - name: http
    targetPort: 8888
    port: 8888
  selector:
    app: jupyter
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: notebook
spec:
  rules:
  - host: jupyter.phenomenal.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: jupyter-service
          servicePort: http
